["ТДТН-10000/110_70У1"]
"sn_hv_mva" = 10
"sn_mv_mva" = 10
"sn_lv_mva" = 10
"vn_hv_kv" = 115.0
"vn_mv_kv" = 38.5
"vn_lv_kv" = 11.0
"vk_hv_percent" = 10.5
"vk_mv_percent" = 6.16
"vk_lv_percent" = 17.3
"vkr_hv_percent" = 0.7
"vkr_mv_percent" = 0.7
"vkr_lv_percent" = 0.7
"pfe_kw" = 27.0
"i0_percent" = 0.9
"shift_mv_degree" = 0
"shift_lv_degree" = 330
"vector_group" = "YNynd"
"tap_side" = "hv"
"tap_neutral" = 0
"tap_min" = -9
"tap_max" = 9
"tap_step_percent" = 1.78
["ТРДН-40000/110_У1"]
"sn_hv_mva" = 40
"sn_mv_mva" = 20
"sn_lv_mva" = 20
"vn_hv_kv" = 115.0
"vn_mv_kv" = 10.5
"vn_lv_kv" = 10.5
"vk_hv_percent" = 10.5
"vk_mv_percent" = 10.5
"vk_lv_percent" = 10.5 #не проверенная инфа
"vkr_hv_percent" = 0.425 #не проверенная инфа
"vkr_mv_percent" = 0.425 #не проверенная инфа
"vkr_lv_percent" = 0.425 #не проверенная инфа
"pfe_kw" = 27.0 #не проверенная инфа
"i0_percent" = 0.9 #не проверенная инфа
"shift_mv_degree" = 0
"shift_lv_degree" = 330
"vector_group" = "YN0yn0d"
"tap_side" = "hv"
"tap_neutral" = 0
"tap_min" = -9 #не проверенная инфа
"tap_max" = 9 #не проверенная инфа
"tap_step_percent" = 1.78 #не проверенная инфа
"p_cu_kw" = 170
["ТРДН-80000/110"]
"sn_hv_mva" = 80
"sn_mv_mva" = 40
"sn_lv_mva" = 40
"vn_hv_kv" = 115.0
"vn_mv_kv" = 6
"vn_lv_kv" = 6
"vk_hv_percent" = 10.5
"vk_mv_percent" = 15
"vk_lv_percent" = 10.5
"vkr_hv_percent" = 0.25 #рассчитано по потерям КЗ
"vkr_mv_percent" = 0.25 #не проверенная инфа
"vkr_lv_percent" = 0.25 #рассчитано по потерям КЗ
"pfe_kw" = 27.0 #не проверенная инфа
"i0_percent" = 0.9 #не проверенная инфа
"shift_mv_degree" = 330
"shift_lv_degree" = 330
"vector_group" = "YNdd"
"tap_side" = "hv"
"tap_neutral" = 0
"tap_min" = -9 #не проверенная инфа
"tap_max" = 9 #не проверенная инфа
"tap_step_percent" = 1.78 #не проверенная инфа
"p_cu_kw" = 170
["ТРДН-63000/110"] #obsidian\work\factory_documentation\Силовые трансформаторы\SIMENS ТРДН-63000-110.pdf
"sn_hv_mva" = 63
"sn_mv_mva" = 31.5
"sn_lv_mva" = 31.5
"vn_hv_kv" = 115.0
"vn_mv_kv" = 6.3
"vn_lv_kv" = 6.3
"vk_hv_percent" = 10 #hv-mv
"vk_mv_percent" = 19 #mv-lv
"vk_lv_percent" = 10 #hv-lv
"vkr_hv_percent" = 0.1746 #рассчитано по потерям КЗ
"vkr_mv_percent" = 0.1746 #рассчитано по потерям КЗ
"vkr_lv_percent" = 0.1746 #рассчитано по потерям КЗ
"vk0_hv_percent" = 10 #hv-mv
"vk0_mv_percent" = 19 #mv-lv
"vk0_lv_percent" = 10 #hv-lv
"vkr0_hv_percent" = 0.1746 #рассчитано по потерям КЗ
"vkr0_mv_percent" = 0.1746 #рассчитано по потерям КЗ
"vkr0_lv_percent" = 0.1746 #рассчитано по потерям КЗ
"pfe_kw" = 30.0 #потери в сердечнике (холостого хода)
"i0_percent" = 0.1 #ток холостого хода
"shift_mv_degree" = 330
"shift_lv_degree" = 330
"vector_group" = "YNdd"
"tap_side" = "hv"
"tap_neutral" = 0
"tap_min" = -9
"tap_max" = 9
"tap_step_percent" = 1.78
"p_cu_kw" = 170
